// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"
)

type OperationType struct {
	ID          int32          `json:"id"`
	Description sql.NullString `json:"description"`
}

type Transaction struct {
	ID            string    `json:"id"`
	AccountID     string    `json:"account_id"`
	OperationType int32     `json:"operation_type"`
	Amount        int32     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
